### ISSUE TITLE
Suggestions to simplify right-click options

### ISSUE THREAD

**Issue by SamuelMiller** [robint99/dock-applet#16]
Hello,
To reduce the clutter of the right-click options for each app icon, I suggest that you move the general dock options (e.g., dock preferences, about, remove from panel, move, lock to panel, etc) to its own minor icon on the far left as it is done with the standard notification area applet in Ubuntu Mate. When one right clicks on any of the notification area icons, only the options specific to each icon appears. General options are available by right-clicking a small icon that looks like three vertically stacked dots on the far left. When I started using the dock-applet, I accidentally removed your dock-applet from the panel at least a couple of times before I learnt that "remove from panel" removes the whole applet instead of the individual icon. The dock's "remove from panel" option behaves differently than the standard/classic launcher applet where "remove from panel" removes the single instance/icon of the launcher applet. Separating the general dock options from the right-click icon options would help remedy this potential confusion for first time users. 

I would also appreciate the option to easily close individual windows of an app, when there is more than one open. This could be done by adding a  click-able "x" beside each of the window names displayed (on the far-right?). As it is now, there is only the option to close all the windows at once. In order for me to close an individual window, I have to right-click on an app's icon, select the windows name and then move the mouse up to the far right of the screen to click on the apps "x" close option.

Thanks again for the app!

**Comment by karas84** [comment]
I agree with almost everything you said. Only thing I'm against with are the small dots a lot of applets have. I get why they do that but I don't like how everything can't be side by side without spacing. I actually use the dock with other widgets and I like how they integrate perfectly. You cannot even notice they are different applets. Adding dots would break that and would be a pity in my opinion. On the other hand I'm totally in for the "x" thing beside each window. Another cool thing would be changing the default behaviour to bring to focus all the windows of a group when clicking on the relative icon on the dock (I usually have A LOT of terminals open and when I want one of them I always end up bringing all of them up), it wolud be useful to do what unity does: bring up only the last used one and use the scroll on your mouse to switch between the others. Obviously this here are my 2 cents only ;) the app is great!

**Comment by robint99** [comment]
Hi SamuelMiller,

I agree, the right click menu is very cluttered and needs to be sorted out and I've got plans to do just that. For example, I'm intending to allow dock icons to be arranged by drag and drop, thus getting rid of the 'Move up, Move down etc' options.  Right now, I'm working on changing the applet's tooltip so that instead of just displaying the apps name, it lists the all of the apps open windows and allows you to select one, and  - at your suggestion - gives you 'x's to click on to easily close the windows. Screenshot below:

![image](https://cloud.githubusercontent.com/assets/10033637/8570601/830b4812-2579-11e5-99cd-6c0b7fd99abe.png)

Once I get this finished, there'll be no need to include a list of windows in the right click menu, and ultimately, the only Items I want in there are the dock Preferences and About dialogs, plus a Pin/Unpin option for the current app. This should greatly simplify things. 

I do take the point about how easy it can be to delete the applet by accident, this has happened to me many times and its extremely annoying to have set the applet up again afterwards. However, the 'Remove from Panel' right click option is supplied by MATE and there's nothing I can do to change the wording or move it about in the menu. As a short term way of working around this, I'm thinking about adding an option on the Preferences dialog to save the applet configuration (launchers and preferences) to a file that can be loaded in again later in case of accidental deletion. In the long term though, I think the best way to prevent accidental deletions is to carry on doing what I'm doing and reduce the number of right click options the applet has. If the user rarely has the need to go the right click menu there'll be much less chance of mis-clicks.

Cheers

**Comment by robint99** [comment]
Hi karas84,

I like your ideas of only bringing back the last used window on clicking a dock icon and using the mouse wheel to cycle through all window, so I'll see about adding them to the applet as soon as I've got a bit of time.

Thanks.

**Comment by helamsirrine** [comment]
Not sure if you can do this, but... I would like to see a context in the default menu to pin launchers to the dock. For example: if I have access a program launcher thru the menu and right click it, I get options to "Add this Launcher to Panel" or "Add this Launcher to Desktop." I would sure like a "Pin this Launcher to Dock" option. It may also be nice to drag and drop launchers from panels or the desktop to the dock area and have them pin rather than dropping as a standard launcher in the area next to the dock. I think these few small changes could really improve integration with the desktop, but I'm not sure how much would have to be done in conjunction with the Mate-Desktop team to make it happen.

**Comment by SamuelMiller** [comment]
Robint99, I look foward to the updates you mention in your post. 
Thank again for all your hard work!
Helamsirrine's suggestion is a good one.
