### ISSUE TITLE
Java programs running with latest oracle8 java never corespond with icon nor name

### ISSUE THREAD

**Issue by freed00m** [robint99/dock-applet#2]
verson: 0.59+git20150512~webupd8~trusty01

Hello, if I try to run matlab R2014a the dock applet shows a "dock_applet.py" with a generic icon
If I run Simulink library it is shown as "Hexchat" 

I have no idea what is going on, since I never even ran hexchat app on linux mint 17.1 latest. 

Another example, if I start PHPstorm it is shown as "Oracle java 8 runtime"

---

How should I proceed ? to give you enough information to fix this issue? It seems it is a Java issue.

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

:)

Processor : 4x AMD A8-4500M APU integrated GPU
Operating System : Linux Mint 17.1 Rebecca (MATE)
OpenGL : AMD Radeon HD 7640G
X11 Vendor : The X.Org Foundation v1.15.1
Kernel : Linux 3.13.0-49-generic (x86_64)

**Comment by robint99** [comment]
Hi,

Thanks for the info. I hadn't actually checked the applet with Java programs. Maybe it would have been a good idea ;) Anyway, I'll start looking into this now....

Cheers,

Robin

**Comment by robint99** [comment]
I've had a look at this now and got PhpStorm working. I've not been able to try it Matlab because they wouldn't let me download an evaluation copy (I was honest and said it was for non-commercial purposes...), however I think the fix I put in place for PhpStorm will probably be good for Matlab too. I've tried some other Java apps in Java 7 and 8, Eclipse, Netbeans, and Freemind and they all work fine with the applet and their icons and names are correct.

I'll be putting a new version of the applet soon, hopefully within the next week, so if you could give it a try with Matlab and let me know if it works or not, that would be cool.

Cheers

**Comment by robint99** [comment]
I've just uploaded V0.61 of the applet to git and the AUR, so hopefully the Webupd8 PPA will also be updated shortly..

**Comment by freed00m** [comment]
Webupd8_ still not there :) I'll test it asap.

**Comment by freed00m** [comment]
Well :) the PhpStorm and other IDEs are now with a default icon from a theme.

The launcher for matlab was created manually, meaning that I selected icon from edit Main-menu box.
So default launcher icon is showing instead of Matlab icon.
That's not a bug but a design issue. No idea how it could be solved.


Yet! Another Java application called SmartGit, free of charge for noncomercial purposes :), is being presented as Oracle 8 Java runtime.

**Comment by robint99** [comment]
Thanks for the info. If you're using a custom launcher for Matlab, does that mean that it doesn't have a .desktop file in /usr/share/applications or ~/.local/share/applications ? If it doesn't, that would explain why the icon isn't recognised, because the applet uses .desktop files to find out which app icons to display.

If you don't have a .desktop file for Matlab, then you can easily create one by copying the example below (I borrowed it from Tilda), change the Exec line to the command used to start Matlab and changing the Icon line to any particular icon you like. 

[Desktop Entry]
Name=Matlab
Exec=/usr/bin/tilda
Icon=/usr/share/pixmaps/tilda.png
Terminal=false
Type=Application

Save this file as matlab.desktop in /usr/share/applications (or ~/.local/share/applications if you prefer), start Matlav and then the applet will hopefully recognize it and give you a nice icon. That'll get you going in the short-term, but I'll probably be adding a 'create custom launcher' option to the next version of the app in case anyone else comes across this problem.

As for Smartgit I'll download it and see if I can sort that out too...

Cheers,


Robin

**Comment by freed00m** [comment]
Hi :)

I have a MATLAB 2014a file (not with ".desktop" as the other launchers) in .local/share/applicaitons it does not have a dedicated icon, because it was created in Mint menu editor. And if you assign a icon from the mint menu editor then it's saved don't know where. 
When Alt+Tabbing matlab has it's own Low resolution icon there, it's not that I chose.

You might find this information usefull. Matlab starts very slowly, so there is a splash screen for about 3minutes, and that splashscreen has no icon also, panel/docky/alttab. My guess is that your dock will load the icon from splashscreen and then when it finishes starting it wont update the icon? maybe?

**Comment by robint99** [comment]
Hello again :)

The way the applet works is that it tries to a find a .desktop file for the app and get the icon from that. If it can't find a .desktop file it looks in /usr/share/pixmaps for an icon with the app's name. If that doesn't work it gives up and used the default one. I suspect that if you added .desktop to your MATLAB 2014a file that might help the applet find it...

I downloaded Smartgit and installed it into my home directory. As you can see below the applet correctly identifies it as Smartgit and not Oracle 8. Which is very odd.

![smartgit1](https://cloud.githubusercontent.com/assets/10033637/8007398/74cad51a-0b93-11e5-8951-427d38dbf678.png)

I'm going to take a look at the code for plank and the taskbar applet as they both seem to find app names and icons even without .desktop files, and see what I can borrow from there ;)

**Comment by freed00m** [comment]
I am running latest build, you can try it via Help -> latest build. It updates it self automaticaly without hassel. 

Now I encountered a weird way to fix the issue.  
I added ".desktop" to a SmarGit in  /.local/share/applications/ , it didn't help and also the launcher in mint menu was also updated to "SmartGit.desktop" so I removed the extension again and after restarting the app the icon was there in your dock and now it works :( I have no idea how could re-renaming the launcher fix the issue but now it works with smartgit. 

If I encouter anything else I will let you know.

**Comment by robint99** [comment]
I've now updated the applet, and made some changes which may help with your problem. 

For apps like Matlab which the dock can't recognise there's a new option available by right clicking the app's icon while the app is running - create custom launcher. This works in the same way as the custom launcher option for the mate panel, you fill in the command to launch the app, set the icon etc. The applet then creates a .desktop file using this info and also using some info gained from the running app which should be enough for the applet to link the app together with the windows it creates. An icon then appears on the dock. The app should then be closed, but after that it can be started and used as normal from the new dock icon.

Of course, since I don't have Matlab I haven't been able to test the custom launcher feature with it. I've instead used a couple of test applications I wrote, plus a few Steam games. So far everything seems to work properly and I'm hopeful that it'll solve your problem with Matlab. But even if not, these custom launchers are also useful for applications which get installed outside of the usual locations and which the applet can't recognise as a result of this, so I've not been wasting my time ;)

Hope this all helps. Let me know how you get on.

**Comment by robint99** [comment]
A bit more info for you... I've now been able to get hold of trial version of Matlab R2015a, and have installed it on Linux Mint 17.1. I don't know how to actually use Matlab (so my testing hasn't been exhaustive), but after creating a custom launcher it all seemed to work properly with the applet, and I could start it, minimize, maximize windows as normal etc.

Screenshot below:

![matlab ss](https://cloud.githubusercontent.com/assets/10033637/8252199/767cbdb8-167b-11e5-8480-7cc49182df1b.png)

**Comment by karas84** [comment]
In response to [this](https://github.com/robint99/dock-applet/issues/1#issuecomment-113480053) comment:

I'm usign Ubuntu (the official one) 14.04. If you need anything else let me know.

**Comment by robint99** [comment]
I've managed to sort this out now. The problem was due to an invalid entry in a .desktop file on Ubuntu 14.04 and I've fixed the applet so it won't fall over if come across this sort of thing. I've commited the fix to github but as the change is minor its not worth releasing a new version for it.

The code changes are listed below if you want to edit the file on your own system. Of, if you'd prefer, let me know your email address and I can just email you the entire file...

in /usr/lib/mate-applets/mate-dock-applet/docked_app.py:

goto line 589 and replace 

                de_exec = the_de.getExec().split(none, 1)[0]

with
                de_exec = the_de.getExec()
                if (de_exec is not None) and (de_exec != ""):
                    de_exec = de_exec.split(None, 1)[0]
                    exec_found = self.cmd_line.find(de_exec) != -1
                else:
                    exec_found = False

and then a few lines further down after the comments, replace

                 if (name_part_found == True) or \
                        (self.cmd_line.find(de_exec) != =1) or \
                        (the_de.getStartupWMClass() == self.wm_class_name):
                    self.desktop_file = srch_dir+the_file
                    return True
with
                if (name_part_found == True) or (exec_found == True) or \
                        (the_de.getStartupWMClass() == self.wm_class_name):
                    self.desktop_file = srch_dir+the_file
                    return True

Save the file, log out and back in and you should find that matlab appears on the dock. Once you've logged into matlab and its loaded up, you'll need to create a custom launcher (when you specify the command, make sure matlab is started with the -desktop option) but from then on you should be good to go.

Let me know how you get on.

Cheers

**Comment by freed00m** [comment]
@robint99  It's a python right? So indent the nested functions? like 

with1
```
de_exec = the_de.getExec()
if (de_exec is not None) and (de_exec != ""):
    de_exec = de_exec.split(None, 1)[0]
    exec_found = self.cmd_line.find(de_exec) != -1
else:
    exec_found = False
```

with2
```
if (name_part_found == True) or (exec_found == True) or \
(the_de.getStartupWMClass() == self.wm_class_name):
    self.desktop_file = srch_dir+the_file
    return True
```

I'll try it soon.

**Comment by robint99** [comment]
Ok. My comment was mainly aimed at Karas84 but I forgot to mark it as such. Feel free to try the applet anyway though ;)

**Comment by karas84** [comment]
@robint99 edited the file and I can confirm it's working. Also things like the window that pops up when you create a custom launcher it's working now. Thanks!

**Comment by robint99** [comment]
No problem. Thanks for all your help with testing!
