### ISSUE TITLE
Launching second (third, etc.) instance of program from pinned icon.

### ISSUE THREAD

**Issue by tevaughan** [robint99/dock-applet#41]
When the corresponding (pinned) application is not already running, clicking its icon on the dock launches an instance of the application. However, for a pinned application such as mate-terminal, I sometimes need to launch a new instance even when there might already be one or more instances running. I've not been able to see how to do this by any combination of mouse clicks on the icon.

I'm running "Dock Applet V0.67" (as reported by 'About...') on Debian unstable.

**Comment by robint99** [comment]
To open a new instance of a running application, what you need to do is press the <shift> key whilst clicking the app's dock icon. It doesn't work will all apps, but it definitely does with Mate Terminal...

In the next version of the applet I'm going to add a 'hints and tips' option to the About dialog specifically so that useful information like this can get passed on to users.

Cheers!

**Comment by tevaughan** [comment]
Thanks! Which key should I press while clicking the icon?

On Wednesday, February 17, 2016, robint99 <notifications@github.com> wrote:

> Closed #41 <https://github.com/robint99/dock-applet/issues/41>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robint99/dock-applet/issues/41#event-553317200>.
>


-- 
Thomas E. Vaughan

**Comment by robint99** [comment]
Either of the shift keys. I did put this in the first message but for some reason it hasn't appeared there....
I'll re-edit it.
