### ISSUE TITLE
Compiling instructions doesn't work on Ubuntu Mate for Raspberry

### ISSUE THREAD

**Issue by kardester** [robint99/dock-applet#8]
I followed the instructions and installed the dependencies "Python3" and "gir1.2-wnck-3.0".
When I put "configure --prefix=/usr" appears an message that say "configure : Comand not found"
I tried installing build-essentials but still the same. Sorry for my bad English.

**Comment by robint99** [comment]
Oops, the instructions are were wrong and should have said
      ./configure -- prefix=/usr
rather than

**Comment by kardester** [comment]
I already tried ./configure but it returns: configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
I solved doing before: "autoreconf -f -i -Wall,no-obsolete" and them I can use the "./configure"
Now I can see the applet on the list but I can't add it to the panel.

**Comment by robint99** [comment]
Thanks for the info about autoreconf. I'm new to developing with autotools and it looks as though I've still got some reading to do ;)

To try and solve your problem with the applet, what you need to do is have a look at /usr/share/dbus-1/services/org.mate.panel.applet.DockAppletFactory.service. Inside this file there will be a line that begins with 'Exec=' and which should contain the location of the main applet file (on my Ubuntu laptop this is /usr/lib/mate-applets/mate-dock-applet/dock_applet.py). Check to make sure that the directory and file are correct. If not, let me know because something has gone wrong with the installation. However, there is a workaround that may get you up and running. if you can find out where dock_applet.py actually is, you can change the DockAppletFactory.service file so that it points to the correct location. If you try adding another dock applet to the panel after that, it should be fine...

If the directory and file in the .service file are correct, cd to the directory and try running 'python3 dock_applet.py'  from the command line. What you should hopefully see is some sort of error message (the warning about Glk 2.0 and python introspection is fine, so you can ignore that). If you do see errors, please please let me know what they are and I'll try to help you further. If you see one or more dock applets appearing on your panel (the number depends on how many times you tried to add the applet from the list) then everything has suddenly started working and something truly weird is happening. 

I haven't got a Pi 2 to try the applet on, but I've just ordered one which should be with me in a few days. As soon as I can I'll give it a try for myself...

**Comment by kardester** [comment]
The location of the main applet file is correct.
This is the output of 'python3 dock_applet.py':
  
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
/usr/share/themes/Yuyo-Dark/gtk-2.0/Apps/libreoffice.rc:40: Imposible encontrar un archivo imagen en pixmap_path: «Entry/entry-border-bg-solid.png»
/usr/share/themes/Yuyo-Dark/gtk-2.0/Apps/libreoffice.rc:43: Background image options specified without filename
/usr/share/themes/Yuyo-Dark/gtk-2.0/Apps/libreoffice.rc:49: Imposible encontrar un archivo imagen en pixmap_path: «Entry/entry-border-active-bg-solid.png»
/usr/share/themes/Yuyo-Dark/gtk-2.0/Apps/libreoffice.rc:52: Background image options specified without filename
Traceback (most recent call last):
  File "dock_applet.py", line 45, in <module>
    gi.require_version("Wnck", "1.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 104, in require_version
    (namespace, version))
ValueError: Namespace Wnck not available for version 1.0

**Comment by robint99** [comment]
I see the problem. You have gir1.2-wnck-3.0 installed but the applet
requires gir1.2-wnck-1.0. Unfortunately gir1.2-wnck-1.0 isn't included in
15.04 so it can't be installed easily. However, there's a version available
for 14.10 which you can download from
http://launchpadlibrarian.net/160438738/gir1.2-wnck-1.0_2.30.7-0ubuntu4_armhf.deb
and which should hopefully work fine.

This is also an issue for x86 but using the older package sorts the problem
out there so hopefully the same will be true on the Pi 2.

Hope this helps....

**Comment by kardester** [comment]
I uninstalled "gir1.2-wnck-3.0" and then installed the package from the link but it doesn't work neither. When I put 'python 3 dock_applet.py' the output don't show the error message but the applet never start.

**Comment by robint99** [comment]
Hi,

This is all working now. I've updated the README.md file with some compilation instructions for the pi 2. I think your problem was probably due to a missing libglib2.0-dev package. Once I installed that on my pi, the applet start working fine.

Cheers.

**Comment by kardester** [comment]
Works great now. Thanks for your work.
